/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crayon_jni_JNITest */

#ifndef _Included_crayon_jni_JNITest
#define _Included_crayon_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crayon_jni_JNITest
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crayon_jni_JNITest_set
  (JNIEnv *, jclass, jint);

/*
 * Class:     crayon_jni_JNITest
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_crayon_jni_JNITest_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
